[2025-07-25T19:16:17.446+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-25T19:16:18.262+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.load_songplays_fact_table scheduled__2025-07-25T12:00:00+00:00 [queued]>
[2025-07-25T19:16:18.501+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.load_songplays_fact_table scheduled__2025-07-25T12:00:00+00:00 [queued]>
[2025-07-25T19:16:18.501+0700] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2025-07-25T19:16:18.785+0700] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_songplays_fact_table> on 2025-07-25 12:00:00+00:00
[2025-07-25T19:16:18.794+0700] {logging_mixin.py:188} WARNING - /home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=20202) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-25T19:16:18.795+0700] {standard_task_runner.py:63} INFO - Started process 20205 to run task
[2025-07-25T19:16:18.793+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_local_postgres_pipeline', 'load_songplays_fact_table', 'scheduled__2025-07-25T12:00:00+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_pjt.py', '--cfg-path', '/tmp/tmp3m11_u_v']
[2025-07-25T19:16:18.795+0700] {standard_task_runner.py:91} INFO - Job 97: Subtask load_songplays_fact_table
[2025-07-25T19:16:23.209+0700] {task_command.py:426} INFO - Running <TaskInstance: etl_local_postgres_pipeline.load_songplays_fact_table scheduled__2025-07-25T12:00:00+00:00 [running]> on host DESKTOP-9M5T9P5.localdomain
[2025-07-25T19:16:27.980+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='phuongnt226' AIRFLOW_CTX_DAG_ID='etl_local_postgres_pipeline' AIRFLOW_CTX_TASK_ID='load_songplays_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-25T12:00:00+00:00'
[2025-07-25T19:16:27.981+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-25T19:16:32.992+0700] {base.py:84} INFO - Using connection ID 'postgres_id' for task execution.
[2025-07-25T19:16:34.499+0700] {sql.py:470} INFO - Running statement: 
        SELECT
                md5(events.sessionid || events.start_time) songplay_id,
                events.start_time, 
                events.userid, 
                events.level, 
                songs.song_id, 
                songs.artist_id, 
                events.sessionid, 
                events.location, 
                events.useragent
                FROM (SELECT TIMESTAMP 'epoch' + ts/1000 * interval '1 second' AS start_time, *
            FROM staging_events
            WHERE page='NextSong') events
            LEFT JOIN staging_songs songs
            ON events.song = songs.title
                AND events.artist = songs.artist_name
                AND events.length = songs.duration
    , parameters: None
[2025-07-25T19:16:34.576+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-25T19:16:34.577+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/dags/etl_pipeline_pjt.py", line 86, in load_songplays_table
    execute_sql(sql_queries.SqlQueries.songplay_table_insert)
  File "/home/ngtph/airflow/dags/etl_pipeline_pjt.py", line 17, in execute_sql
    hook.run(sql_statement)
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 418, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 475, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFunction: operator does not exist: integer || timestamp without time zone
LINE 3:                 md5(events.sessionid || events.start_time) s...
                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

[2025-07-25T19:16:35.294+0700] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_local_postgres_pipeline, task_id=load_songplays_fact_table, run_id=scheduled__2025-07-25T12:00:00+00:00, execution_date=20250725T120000, start_date=20250725T121618, end_date=20250725T121635
[2025-07-25T19:16:35.636+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 97 for task load_songplays_fact_table (operator does not exist: integer || timestamp without time zone
LINE 3:                 md5(events.sessionid || events.start_time) s...
                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
; 20205)
[2025-07-25T19:16:35.671+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-25T19:16:36.496+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-07-25T20:10:08.813+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-25T20:10:10.019+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.load_songplays_fact_table scheduled__2025-07-25T12:00:00+00:00 [queued]>
[2025-07-25T20:10:10.188+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.load_songplays_fact_table scheduled__2025-07-25T12:00:00+00:00 [queued]>
[2025-07-25T20:10:10.188+0700] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2025-07-25T20:10:10.413+0700] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_songplays_fact_table> on 2025-07-25 12:00:00+00:00
[2025-07-25T20:10:10.422+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_local_postgres_pipeline', 'load_songplays_fact_table', 'scheduled__2025-07-25T12:00:00+00:00', '--job-id', '165', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_pjt.py', '--cfg-path', '/tmp/tmpksddec2f']
[2025-07-25T20:10:10.424+0700] {standard_task_runner.py:91} INFO - Job 165: Subtask load_songplays_fact_table
[2025-07-25T20:10:10.424+0700] {logging_mixin.py:188} WARNING - /home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=21238) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-25T20:10:10.424+0700] {standard_task_runner.py:63} INFO - Started process 21242 to run task
[2025-07-25T20:10:13.640+0700] {task_command.py:426} INFO - Running <TaskInstance: etl_local_postgres_pipeline.load_songplays_fact_table scheduled__2025-07-25T12:00:00+00:00 [running]> on host DESKTOP-9M5T9P5.localdomain
[2025-07-25T20:10:19.398+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='phuongnt226' AIRFLOW_CTX_DAG_ID='etl_local_postgres_pipeline' AIRFLOW_CTX_TASK_ID='load_songplays_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-25T12:00:00+00:00'
[2025-07-25T20:10:19.399+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-25T20:10:20.234+0700] {base.py:84} INFO - Using connection ID 'postgres_id' for task execution.
[2025-07-25T20:10:20.914+0700] {sql.py:470} INFO - Running statement: 
        SELECT
                md5(events.sessionid || events.start_time) songplay_id,
                events.start_time, 
                events.userid, 
                events.level, 
                songs.song_id, 
                songs.artist_id, 
                events.sessionid, 
                events.location, 
                events.useragent
                FROM (SELECT TIMESTAMP 'epoch' + ts/1000 * interval '1 second' AS start_time, *
            FROM staging_events
            WHERE page='NextSong') events
            LEFT JOIN staging_songs songs
            ON events.song = songs.title
                AND events.artist = songs.artist_name
                AND events.length = songs.duration
    , parameters: None
[2025-07-25T20:10:21.042+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-25T20:10:21.043+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/dags/etl_pipeline_pjt.py", line 86, in load_songplays_table
    execute_sql(sql_queries.SqlQueries.songplay_table_insert)
  File "/home/ngtph/airflow/dags/etl_pipeline_pjt.py", line 17, in execute_sql
    hook.run(sql_statement)
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 418, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 475, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFunction: operator does not exist: integer || timestamp without time zone
LINE 3:                 md5(events.sessionid || events.start_time) s...
                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

[2025-07-25T20:10:21.658+0700] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_local_postgres_pipeline, task_id=load_songplays_fact_table, run_id=scheduled__2025-07-25T12:00:00+00:00, execution_date=20250725T120000, start_date=20250725T131010, end_date=20250725T131021
[2025-07-25T20:10:21.933+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 165 for task load_songplays_fact_table (operator does not exist: integer || timestamp without time zone
LINE 3:                 md5(events.sessionid || events.start_time) s...
                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
; 21242)
[2025-07-25T20:10:21.953+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-25T20:10:22.699+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
