[2025-07-26T08:53:32.663+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-26T08:53:39.924+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.load_time_dim_table manual__2025-07-25T18:16:00.933196+00:00 [queued]>
[2025-07-26T08:53:40.612+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.load_time_dim_table manual__2025-07-25T18:16:00.933196+00:00 [queued]>
[2025-07-26T08:53:40.613+0700] {taskinstance.py:2306} INFO - Starting attempt 2 of 5
[2025-07-26T08:53:41.215+0700] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_time_dim_table> on 2025-07-25 18:16:00.933196+00:00
[2025-07-26T08:53:41.221+0700] {logging_mixin.py:188} WARNING - /home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=6414) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-26T08:53:41.222+0700] {standard_task_runner.py:63} INFO - Started process 6430 to run task
[2025-07-26T08:53:41.221+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_local_postgres_pipeline', 'load_time_dim_table', 'manual__2025-07-25T18:16:00.933196+00:00', '--job-id', '507', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_pjt.py', '--cfg-path', '/tmp/tmpu4flrh78']
[2025-07-26T08:53:41.222+0700] {standard_task_runner.py:91} INFO - Job 507: Subtask load_time_dim_table
[2025-07-26T08:53:52.010+0700] {task_command.py:426} INFO - Running <TaskInstance: etl_local_postgres_pipeline.load_time_dim_table manual__2025-07-25T18:16:00.933196+00:00 [running]> on host DESKTOP-9M5T9P5.localdomain
[2025-07-26T08:54:07.343+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='phuongnt226' AIRFLOW_CTX_DAG_ID='etl_local_postgres_pipeline' AIRFLOW_CTX_TASK_ID='load_time_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T18:16:00.933196+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-25T18:16:00.933196+00:00'
[2025-07-26T08:54:07.344+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-26T08:54:09.852+0700] {base.py:84} INFO - Using connection ID 'postgres_id' for task execution.
[2025-07-26T08:54:10.721+0700] {sql.py:470} INFO - Running statement: 
    INSERT INTO time (start_time, hour, day, week, month, year, weekday)
    SELECT 
        start_time, 
        EXTRACT(hour FROM start_time), 
        EXTRACT(day FROM start_time), 
        EXTRACT(week FROM start_time), 
        EXTRACT(month FROM start_time), 
        EXTRACT(year FROM start_time), 
        EXTRACT(dow FROM start_time)
    FROM songplays
    ON CONFLICT (start_time) DO NOTHING                     
, parameters: None
[2025-07-26T08:54:15.695+0700] {sql.py:479} INFO - Rows affected: 0
[2025-07-26T08:54:15.909+0700] {logging_mixin.py:188} INFO - Executed SQL: 
    INSERT INTO time (start_time, hour, day, week... -> Result: None
[2025-07-26T08:54:15.909+0700] {python.py:237} INFO - Done. Returned value was: None
[2025-07-26T08:54:15.910+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-26T08:54:18.702+0700] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_local_postgres_pipeline, task_id=load_time_dim_table, run_id=manual__2025-07-25T18:16:00.933196+00:00, execution_date=20250725T181600, start_date=20250726T015339, end_date=20250726T015418
[2025-07-26T08:54:32.569+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-26T08:54:35.690+0700] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-26T08:54:36.194+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
