[2025-07-26T00:16:17.685+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-26T00:16:18.503+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.stage_songs scheduled__2025-07-25T17:00:00+00:00 [queued]>
[2025-07-26T00:16:18.684+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.stage_songs scheduled__2025-07-25T17:00:00+00:00 [queued]>
[2025-07-26T00:16:18.684+0700] {taskinstance.py:2306} INFO - Starting attempt 4 of 4
[2025-07-26T00:16:18.962+0700] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): stage_songs> on 2025-07-25 17:00:00+00:00
[2025-07-26T00:16:18.970+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_local_postgres_pipeline', 'stage_songs', 'scheduled__2025-07-25T17:00:00+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_pjt.py', '--cfg-path', '/tmp/tmpjmjat_xj']
[2025-07-26T00:16:18.972+0700] {standard_task_runner.py:91} INFO - Job 206: Subtask stage_songs
[2025-07-26T00:16:18.973+0700] {logging_mixin.py:188} WARNING - /home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1859) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-26T00:16:18.974+0700] {standard_task_runner.py:63} INFO - Started process 1860 to run task
[2025-07-26T00:16:23.439+0700] {task_command.py:426} INFO - Running <TaskInstance: etl_local_postgres_pipeline.stage_songs scheduled__2025-07-25T17:00:00+00:00 [running]> on host DESKTOP-9M5T9P5.localdomain
[2025-07-26T00:16:28.382+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='phuongnt226' AIRFLOW_CTX_DAG_ID='etl_local_postgres_pipeline' AIRFLOW_CTX_TASK_ID='stage_songs' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-25T17:00:00+00:00'
[2025-07-26T00:16:28.384+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-26T00:16:29.472+0700] {base.py:84} INFO - Using connection ID 'postgres_id' for task execution.
[2025-07-26T00:16:30.168+0700] {logging_mixin.py:188} INFO - Found 71 song files.
[2025-07-26T00:16:30.282+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-26T00:16:30.283+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/dags/etl_pipeline_pjt.py", line 38, in stage_songs_to_postgres
    cur.execute("SELECT 1 FROM staging_log WHERE file_path = %s", (file_path,))
psycopg2.errors.UndefinedTable: relation "staging_log" does not exist
LINE 1: SELECT 1 FROM staging_log WHERE file_path = '/home/ngtph/air...
                      ^

[2025-07-26T00:16:30.994+0700] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_local_postgres_pipeline, task_id=stage_songs, run_id=scheduled__2025-07-25T17:00:00+00:00, execution_date=20250725T170000, start_date=20250725T171618, end_date=20250725T171630
[2025-07-26T00:16:31.299+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 206 for task stage_songs (relation "staging_log" does not exist
LINE 1: SELECT 1 FROM staging_log WHERE file_path = '/home/ngtph/air...
                      ^
; 1860)
[2025-07-26T00:16:33.477+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-26T00:16:34.256+0700] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-26T00:16:34.346+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
