[2025-07-26T00:05:32.255+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-26T00:05:33.125+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.stage_songs scheduled__2025-07-25T17:00:00+00:00 [queued]>
[2025-07-26T00:05:33.369+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.stage_songs scheduled__2025-07-25T17:00:00+00:00 [queued]>
[2025-07-26T00:05:33.369+0700] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2025-07-26T00:05:33.691+0700] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): stage_songs> on 2025-07-25 17:00:00+00:00
[2025-07-26T00:05:33.702+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_local_postgres_pipeline', 'stage_songs', 'scheduled__2025-07-25T17:00:00+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_pjt.py', '--cfg-path', '/tmp/tmpg44m3jgb']
[2025-07-26T00:05:33.705+0700] {standard_task_runner.py:91} INFO - Job 204: Subtask stage_songs
[2025-07-26T00:05:33.705+0700] {logging_mixin.py:188} WARNING - /home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1753) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-26T00:05:33.706+0700] {standard_task_runner.py:63} INFO - Started process 1757 to run task
[2025-07-26T00:05:36.155+0700] {task_command.py:426} INFO - Running <TaskInstance: etl_local_postgres_pipeline.stage_songs scheduled__2025-07-25T17:00:00+00:00 [running]> on host DESKTOP-9M5T9P5.localdomain
[2025-07-26T00:05:41.394+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='phuongnt226' AIRFLOW_CTX_DAG_ID='etl_local_postgres_pipeline' AIRFLOW_CTX_TASK_ID='stage_songs' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-25T17:00:00+00:00'
[2025-07-26T00:05:41.395+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-26T00:05:42.450+0700] {base.py:84} INFO - Using connection ID 'postgres_id' for task execution.
[2025-07-26T00:05:43.082+0700] {logging_mixin.py:188} INFO - Found 71 song files.
[2025-07-26T00:05:43.188+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-26T00:05:43.189+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/dags/etl_pipeline_pjt.py", line 38, in stage_songs_to_postgres
    cur.execute("SELECT 1 FROM staging_log WHERE file_path = %s", (file_path,))
psycopg2.errors.UndefinedTable: relation "staging_log" does not exist
LINE 1: SELECT 1 FROM staging_log WHERE file_path = '/home/ngtph/air...
                      ^

[2025-07-26T00:05:45.038+0700] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_local_postgres_pipeline, task_id=stage_songs, run_id=scheduled__2025-07-25T17:00:00+00:00, execution_date=20250725T170000, start_date=20250725T170533, end_date=20250725T170545
[2025-07-26T00:05:45.812+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 204 for task stage_songs (relation "staging_log" does not exist
LINE 1: SELECT 1 FROM staging_log WHERE file_path = '/home/ngtph/air...
                      ^
; 1757)
[2025-07-26T00:05:47.027+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-26T00:05:47.934+0700] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-26T00:05:47.988+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
