[2025-07-25T18:54:59.918+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-25T18:55:01.727+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.load_songplays_fact_table scheduled__2025-07-25T11:00:00+00:00 [queued]>
[2025-07-25T18:55:02.080+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.load_songplays_fact_table scheduled__2025-07-25T11:00:00+00:00 [queued]>
[2025-07-25T18:55:02.081+0700] {taskinstance.py:2306} INFO - Starting attempt 4 of 4
[2025-07-25T18:55:02.638+0700] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_songplays_fact_table> on 2025-07-25 11:00:00+00:00
[2025-07-25T18:55:02.658+0700] {logging_mixin.py:188} WARNING - /home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=19781) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-25T18:55:02.660+0700] {standard_task_runner.py:63} INFO - Started process 19787 to run task
[2025-07-25T18:55:02.658+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_local_postgres_pipeline', 'load_songplays_fact_table', 'scheduled__2025-07-25T11:00:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_pjt.py', '--cfg-path', '/tmp/tmpolpwmu67']
[2025-07-25T18:55:02.661+0700] {standard_task_runner.py:91} INFO - Job 78: Subtask load_songplays_fact_table
[2025-07-25T18:55:08.487+0700] {task_command.py:426} INFO - Running <TaskInstance: etl_local_postgres_pipeline.load_songplays_fact_table scheduled__2025-07-25T11:00:00+00:00 [running]> on host DESKTOP-9M5T9P5.localdomain
[2025-07-25T18:55:16.212+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='phuongnt226' AIRFLOW_CTX_DAG_ID='etl_local_postgres_pipeline' AIRFLOW_CTX_TASK_ID='load_songplays_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-25T11:00:00+00:00'
[2025-07-25T18:55:16.213+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-25T18:55:16.250+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-25T18:55:16.252+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/dags/etl_pipeline_pjt.py", line 82, in load_songplays_table
    execute_sql(sql_queries.songplay_table_insert)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'helpers.sql_queries' has no attribute 'songplay_table_insert'
[2025-07-25T18:55:17.086+0700] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_local_postgres_pipeline, task_id=load_songplays_fact_table, run_id=scheduled__2025-07-25T11:00:00+00:00, execution_date=20250725T110000, start_date=20250725T115501, end_date=20250725T115517
[2025-07-25T18:55:17.458+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 78 for task load_songplays_fact_table (module 'helpers.sql_queries' has no attribute 'songplay_table_insert'; 19787)
[2025-07-25T18:55:18.654+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-25T18:55:19.455+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
